version: '3.8'

services:
  gateway:
    build: .
    image: shareit/gateway
    container_name: my-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      #- TZ=Europe/Moscow

  server:
    build: .
    image: shareit/server
    container_name: my-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - spring_datasource_username=test
      - spring_datasource_password=test
      #- TZ=Europe/Moscow

  db:
    image: postgres:13.7-alpine
    container_name: my-database
    ports:
      - "6541:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

volumes:
  dbdata:

